"""Initial migration

Revision ID: 1b497f3ec495
Revises: 
Create Date: 2026-04-01 13:01:32.947496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b497f3ec495'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text_id')
    )
    op.create_index('idx_text_id', 'texts', ['text_id'], unique=False)
    op.create_index(op.f('ix_texts_id'), 'texts', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('avatar_file', sa.String(length=256), nullable=True),
    sa.Column('tags', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_author_id', 'tasks', ['author_id'], unique=False)
    op.create_index('idx_tags', 'tasks', ['tags'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('VIEW', 'LIKE', 'CREATE', name='event'), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_task', 'interactions', ['user_id', 'task_id'], unique=False)
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_index('idx_user_task', table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index('idx_tags', table_name='tasks')
    op.drop_index('idx_author_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('idx_username', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_texts_id'), table_name='texts')
    op.drop_index('idx_text_id', table_name='texts')
    op.drop_table('texts')
    # ### end Alembic commands ###
